### PR TITLE
Add splash screen

### PR DESCRIPTION
**Pull request by benfrankel**
Fixes https://github.com/TheBevyFlock/bevy-template/issues/58.

Minimal implementation. Features the Bevy logo from here: https://github.com/bevyengine/bevy/blob/main/assets/branding/bevy_logo_dark.png

### CODE REVIEW

**Review by janhohenheim — COMMENTED** [review]
Code looks good, I'll approve once I see how it looks while running it on my machine

**Comment by benfrankel** [comment]
Expect it to be pretty jarring with no fade in / out :P

**Review by janhohenheim — CHANGES_REQUESTED** [review]
It's blue for a split-second before the splash screen appears on Windows, but I think that's because of the missing deflicker hack. Still, it might be good to have the `ClearColor` match the splash to be sure.

**Comment by benfrankel** [comment]
> It's blue for a split-second before the splash screen appears on Windows, but I think that's because of the missing deflicker hack. Still, it might be good to have the `ClearColor` match the splash to be sure.

Added `ClearColor` in `screen/splash.rs` with a comment explaining it, since it's a workaround for a bug.

**Review by janhohenheim — APPROVED** [review]
Perfect, thanks!

**Review by MiniaczQ — APPROVED** [review]

**Pull request merged**
